### ISSUE TITLE
ClassCastException: class java.lang.Double cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by duclad** [alejandro-du/crudui#116]
Hi guys,

please help me with this:

I have a form defined like
```
      CrudFormFactory<WorkplaceDto>  formFactory = new DefaultCrudFormFactory<>(
             WorkplaceDto.class,
             new  FormLayout.ResponsiveStep("0", 1), 
             new FormLayout.ResponsiveStep("320px", 2), 
             new   FormLayout.ResponsiveStep("600px", 2))
         {
                      @Override
                      protected void configureForm(FormLayout formLayout, List<HasValueAndElement> fields) {
                          Component addressField = (Component) fields.get(0);
                          formLayout.setColspan(addressField, 2);
                      }
           };
        formFactory.setVisibleProperties("address", "lat", "lng");
        NumberField latitudeField = new NumberField();
        NumberField longitudeField = new NumberField();
        AddressPopup addressPopup = new AddressPopup(localityApiClient);
        addressPopup.addSaveChangesListener(addressDto -> {
            AddressCoordinates addressCoordinates = geoLocationApiClient.getAddressCoordinates(addressDto.toString());
            latitudeField.setValue(addressCoordinates.getLatitude());
            longitudeField.setValue(addressCoordinates.getLongitude());
        });
        formFactory.setFieldProvider("address", addressPopup);
        formFactory.setFieldProvider(WorkplaceDto.Fields.lat, o -> latitudeField);
        formFactory.setFieldProvider(WorkplaceDto.Fields.lng, o-> longitudeField);
        formFactory.setUseBeanValidation(true);
        grid.setCrudFormFactory(formFactory);
```

And the DTO as :

```
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@FieldNameConstants
public class WorkplaceDto implements Serializable, HasAddress {
    private Long id;
    private Double lat;
    private Double lng;
    @NotNull
    private CompanyDto company;
    private Long version;
    @NotNull
    private AddressDto address;
```

But when I am running it I get this error:

```	
at com.vaadin.flow.component.textfield.AbstractNumberField.setValue(AbstractNumberField.java:348) ~[vaadin-text-field-flow-23.3.5.jar:na]
	at ing.optimaiz.application.drivs.ui.views.company.WorkplacesPage.lambda$new$0(WorkplacesPage.java:46) ~[classes/:na]
	at ing.optimaiz.application.drivs.ui.components.AddressPopup.saveAddressChanges(AddressPopup.java:71) ~[classes/:na]
	at ing.optimaiz.application.drivs.ui.components.AddressPopup.lambda$openAddressEditDialog$9b1b5227$1(AddressPopup.java:64) ~[classes/:na]
	at org.vaadin.crudui.form.AbstractAutoGeneratedCrudFormFactory.lambda$buildOperationButton$521142cc$1(AbstractAutoGeneratedCrudFormFactory.java:323) ~[crudui-6.2.0.jar:6.2.0]
	... 119 common frames omitted
Caused by: java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap')
	at com.vaadin.flow.data.converter.StringToDoubleConverter.convertToModel(StringToDoubleConverter.java:40) ~[flow-data-23.3.3.jar:23.3.3]
	at com.vaadin.flow.data.converter.Converter$2.lambda$convertToModel$6b579330$1(Converter.java:165) ~[flow-data-23.3.3.jar:23.3.3]
	at com.vaadin.flow.data.binder.SimpleResult.flatMap(SimpleResult.java:65) ~[flow-data-23.3.3.jar:23.3.3]
	at com.vaadin.flow.data.binder.ValidationResultWrap.flatMap(ValidationResultWrap.java:67) ~[flow-data-23.3.3.jar:23.3.3]
	at com.vaadin.flow.data.converter.Converter$2.convertToModel(Converter.java:165) ~[flow-data-23.3.3.jar:23.3.3]
	at com.vaadin.flow.data.converter.Converter$2.convertToModel(Converter.java:163) ~[flow-data-23.3.3.jar:23.3.3]
	at com.vaadin.flow.data.converter.Converter$2.convertToModel(Converter.java:163) ~[flow-data-23.3.3.jar:23.3.3]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$doConversion$0(Binder.java:1316) ~[flow-data-23.3.3.jar:23.3.3]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1560) ~[flow-data-23.3.3.jar:23.3.3]
```

**Comment by alejandro-du** [comment]
What have you tried? Also, please simplify the example to include only the minimal runnable code needed to reproduce the issue. Make sure it compiles. That way anyone interested in helping can reproduce the problem you have and try to help you. Cheers!
