### ISSUE TITLE
Problem with using IntegerField (strange ClassCastException)

### ISSUE THREAD

**Issue by mgodbole** [alejandro-du/crudui#136]
Hi!
I have just started to learn Vaadin, so please bear with me.

I am using GridCrud (awesome add on @alejandro-du , thank you!)
In the editor, I wish to use the IntegerField as I love the UI (steps, helper text etc).
But I am getting a strange (to me at least) ClassCastException.

Here are the details:

**The Entity**
```
@Entity
public class Movie {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull(message = "Movie name required")
    @NotBlank(message = "Movie name required")
    private String name;

    @NotNull(message = "Rating required")
    @Min(value = 0, message = "Rating should be between 0-10")
    @Max(value = 10, message = "Rating should be between 0-10")
    private Integer rating;

    public Movie() {
	// TODO Auto-generated constructor stub
    }

    public Movie(String name, Integer rating) {
	this.name = name;
	this.rating = rating;
    }
    
    //Getter setter etc omitted
}
```

**The view**

```
@Route(value = "")
@PageTitle("GridCrud Test")
public class MainView extends VerticalLayout {

    public MainView(MovieService service) {
	var crud = new GridCrud<>(Movie.class, service);

	// Extract form
	var form = crud.getCrudFormFactory();
	form.setUseBeanValidation(true);

	// Customize form
	form.setVisibleProperties("name", "rating");

	form.setFieldProvider("rating", movie -> {
	    var ratingField = new IntegerField("Rating");
	    ratingField.setMin(0);
	    ratingField.setMax(10);
	    ratingField.setStepButtonsVisible(true);
	    ratingField.setHelperText("Rating out of 10");

	    return ratingField;
	});

	setSizeFull();
	add(new H2("Movie database"), crud);
    }

}
```

**The UX**
1. When I click on the "Add" button, the editor pops up and the IntegerField shows up correctly, but after entering the values (validation runs correctly) I get the ClassCastException.
2. On the other hand if I click on the "Edit" button, the editor does not show at all! (Same exception)

> com.vaadin.flow.data.binder.BindingException: An exception has been thrown inside binding logic for the field element [label='Rating']
> 
> Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
> 	at com.vaadin.flow.component.textfield.AbstractNumberField.**setValue**(AbstractNumberField.java:40) ~[vaadin-text-field-flow-24.4.9.jar:na]
> 	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$convertAndSetFieldValue$4(Binder.java:1572) ~[flow-data-24.4.6.jar:24.4.6]
> 	at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1673) ~[flow-data-24.4.6.jar:24.4.6]
> 

Looks like the issue is with **setValue** which is not making sense to me.
Any pointers to help guide me in the right direction?

Thank you

![1](https://github.com/user-attachments/assets/273f88b1-d950-4cb8-ad03-b2e2b6150a2c)

**Comment by llskyhi** [comment]
Hi,
I encountered similar issue and wrote a MRE at [llskyhi/crudui-issue-136-mre](https://github.com/llskyhi/crudui-issue-136-mre).

*(The MRE uses crudui 7.1.2 while the links below uses 7.1.0.)*

After debugging and viewing source code, I'm pretty sure it's because for number-typed properties, `DefaultCrudFormFactory`
- builds a `TextFiled` ([`DefaultFieldProvider.java#L44`](https://github.com/alejandro-du/crudui/blob/dd024123e6ec7b7ecff59d6771a4be134398f60d/add-on/src/main/java/org/vaadin/crudui/form/impl/field/provider/DefaultFieldProvider.java#L44))
- applies a `AbstractStringToNumberConverter` on the field bound to the property ([`AbstractAutoGeneratedCrudFormFactory.java#L283`](https://github.com/alejandro-du/crudui/blob/dd024123e6ec7b7ecff59d6771a4be134398f60d/add-on/src/main/java/org/vaadin/crudui/form/AbstractAutoGeneratedCrudFormFactory.java#L283))

However when you call `CrudFormFactory#setFieldProvider` to provide a `Integer`-typed field, the `AbstractStringToNumberConverter` still applies.

A workaround to this is to **simultaneously call `CrudFormFactory#setConverter` with a no-op converter**, maybe like
```Java
gridCrud.getCrudFormFactory().setConverter("age", Converter.from(
    presentation -> presentation, // pass through
    model -> model // pass-through
));
```
seems this avoids the default converter to apply ([AbstractAutoGeneratedCrudFormFactory.java#L268](https://github.com/alejandro-du/crudui/blob/dd024123e6ec7b7ecff59d6771a4be134398f60d/add-on/src/main/java/org/vaadin/crudui/form/AbstractAutoGeneratedCrudFormFactory.java#L268)).

Similar issue also happens with other property types, for example setting a `Character`-typed field provider to a `Character` property, which by default also gets `TextField` and `StringToCharacterConverter` applies. 
Setting a no-op converter also workarounds.

Hope this helps!

**Comment by alejandro-du** [comment]
[81d77a3](https://github.com/alejandro-du/crudui/commit/81d77a3b73c6678306f15022ceae5be095e773ec) should fix this. See also: #127

**Comment by alejandro-du** [comment]
Thanks a lot for the detailed report. I just published version 7.2.0 which should fix the problem. Please let me know if the issue persists.
