### ISSUE TITLE
When used in version 8.6 it fails with an exception NoSuchMethodError: com.vaadin.ui.Grid.asSingleSelect()

### ISSUE THREAD

**Issue by bonifacechacha** [alejandro-du/crudui#42]
Below is a sample exception occuring when instaciating with constructor GridCrud(Class<T> domainType, CrudLayout crudLayout)

```
Caused by: java.lang.NoSuchMethodError: com.vaadin.ui.Grid.asSingleSelect()Lcom/vaadin/ui/SingleSelect;
	at org.vaadin.crudui.crud.impl.GridCrud.updateButtons(GridCrud.java:128)
	at org.vaadin.crudui.crud.impl.GridCrud.initLayout(GridCrud.java:89)
	at org.vaadin.crudui.crud.impl.GridCrud.<init>(GridCrud.java:60)
	at org.vaadin.crudui.crud.impl.GridCrud.<init>(GridCrud.java:43)
```

**Comment by alejandro-du** [comment]
Thanks for reporting. Fixed in version 2.3.1.
