### ISSUE TITLE
java.lang.NoSuchMethodError: 'void com.vaadin.flow.component.grid.Grid.setItems(java.util.Collection)' with Vaadin 17.0.1

### ISSUE THREAD

**Issue by vacax** [alejandro-du/crudui#77]
The library stopped working when I upgraded to Vaadin 17.0.1:

Caused by: java.lang.NoSuchMethodError: 'void com.vaadin.flow.component.grid.Grid.setItems(java.util.Collection)'
        at org.vaadin.crudui.crud.impl.GridCrud.refreshGrid(GridCrud.java:122) ~[crudui-4.3.1.jar:4.3.1]
        at org.vaadin.crudui.crud.impl.GridCrud.onAttach(GridCrud.java:91) ~[crudui-4.3.1.jar:4.3.1]
        at com.vaadin.flow.component.ComponentUtil.onComponentAttach(ComponentUtil.java:230) ~[flow-server-4.0.1.jar:4.0.1]
        at com.vaadin.flow.internal.nodefeature.ComponentMapping.lambda$onAttach$0(ComponentMapping.java:102) ~[flow-server-4.0.1.jar:4.0.1]
        at java.base/java.util.Optional.ifPresent(Optional.java:183) ~[na:na]

**Comment by alejandro-du** [comment]
Thanks for reporting. I still have to decide whether to support the latest version or the latest LTS version of Vaadin. Unfortunately, I don't have the time to support both atm. Follow this issue to get notified when the fix is ready. In the meantime, you could try compiling the project yourself using V17.

**Comment by vacax** [comment]
Thank you I will be testing and reporting

**Comment by Thibstars** [comment]
> Thank you I will be testing and reporting

@vacax have you been able to compile the project using V17 yet?

Seems to me there is an issue in `org.vaadin.crudui.form.impl.field.provider.CheckBoxGroupProvider`, since `CheckboxGroup `implements `HasDataView `instead of `HasItems`.

**Comment by alejandro-du** [comment]
The add-on only supports LTS versions (currently the 14 series).

**Comment by bonifacechacha** [comment]
You can [this fork](https://github.com/bonifacechacha/crudui) for vaadin 19

**Comment by alejandro-du** [comment]
Version 4.5.0 should fix this
